### ISSUE TITLE
[BUG] requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by diractorhm** [horstoeko/zugferd-laravel#3]
**Describe the bug**

When I try to install the package into an existing laravel project by running `composer require horstoeko/zugferd-laravel` I get the following error:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires horstoeko/zugferd-laravel * -> satisfiable by horstoeko/zugferd-laravel[v1.0.0, v1.0.1, v1.0.2, v1.0.3].
    - horstoeko/zugferd-laravel[v1.0.0, ..., v1.0.3] require symfony/yaml ^5.3|^6.0 -> found symfony/yaml[v5.3.0, ..., v5.4.44, v6.0.0, ..., v6.4.12] but the package is fixed to v7.1.5 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require horstoeko/zugferd-laravel:*" to figure out if any version is installable, or "composer require horstoeko/zugferd-laravel:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**To Reproduce**

1. Start a new laravel project using the latest version, i.e. by [using docker](https://laravel.com/docs/11.x/installation#docker-installation-using-sail)
2. Then try to install the package by running `./vendor/bin/sail composer require horstoeko/zugferd-laravel`

**Expected behavior**

I would have expected that the package runs with the latest version of laravel and its dependencies.

**Additional information:**
 - OS: macOS
 - OS-Version: 14.6.1
 - PHP-Version: 8.3

**Comment by horstoeko** [comment]
Hi @diractorhm,

thank you for your issue. I will provide a fix as soon I get the time to do that.

Kind regards

**Comment by diractorhm** [comment]
Cool, thanks a lot :)
